WIP: Work towards actually reproducible tests
mozilla/libdmg-hfsplus pull request #10
Opened 2024-09-05 08:12 UTC by vasi

Fixes a number of issues with tests:
* It wasn't documented how to run tests! Add a section to the README
* attribution.t was failing due to random numbers used in dmg creation differing across platforms. Switch to a cross-platform-consistent RNG.
* attribution_full_length.t was failing due to whitespace differences in `wc` output. Fix with regex.
* run_spanning_reference.t was failing since timestamps embedded in HFS+ may or may not differ, depending whether our test crosses a second boundary!? Fix by ignoring lines with timestamps.
* Running multiple tests at a time could fail, as as tests tend to use the same paths. So eg: `mkdir staging` or similar would fail if another test already ran. Fix by making staging/output/reference dirs all independent.

Issues that remain:
* run_spanning.t still fails. Some of this is cuz of randomness, but there may be other reasons too. I'm not really sure what this test is trying to prove, and diffs-of-diffs-of-base64-encoded-plists hurt my brain!

cc @bhearsum

2024-09-05 20:22 UTC, bhearsum requested changes
A couple overall comments:
* The `reference` tests are not so much proper tests, but scripts that generate the associated reference objects to support other tests. Due to their reliance on `hdiutil` and `xattr` they could only possibly work on macOS, of course. `attribution_reference.t` and `hfs_attrs_reference.t` still pass for me on my Sonoma machine. `run_spanning_reference.t` has a very tiny difference, which I can't account for. It's a diff of HFS filesystems - so the randomness in the koly block shouldn't be a factor.
* The other tests only need to pass on Linux, and in fact, most of them still appear to pass when run individually -- it's only when run in parallel that some of them fail. In retrospect, this is probably because of shared state between the tests (I must never have run them as a batch before...). That's something you're obviously correcting here. Please make sure they pass on Linux though - your work here seems to make them pass on macOS but not on Linux, which is the platform we actually use these tools on in production.

I suspect that you'll find that if you only apply the `OUTPUT_DIR` parts that the non-reference tests will begin passing if you run on Linux (or in a docker container).

2024-09-05 20:22 UTC, bhearsum commented on dmg/dmglib.c
> +	koly.fUDIFSegmentID.data1 = reproRand();
I'm not knowledgeable enough to know whether or not there will be harmful side effects to doing this. Out of sheer risk aversion I'm inclined to say that we shouldn't be doing this, unless there's a way to dependency inject or otherwise only use `reproRand` when running tests.

2024-09-06 23:44 UTC, vasi commented on dmg/dmglib.c
> +	koly.fUDIFSegmentID.data1 = reproRand();
I mean, we already know `rand()` is inconsistent between platforms.

2024-09-12 00:42 UTC, vasi commented
You can see what a failure would look like here: https://github.com/vasi/libdmg-hfsplus/actions/runs/10821952386/job/30024971368
And what a pass would look like here: https://github.com/vasi/libdmg-hfsplus/actions/runs/10819948961/job/30018934719

2024-09-12 01:02 UTC, vasi commented
We got crossed wires and both added GHA, woops. Closing this in favor of what's in the mozilla branch.

2024-09-12 01:02 UTC, closed without merging